language: java
jdk: oraclejdk7

env:
  - TERM=dumb
  - BUILD_TOOLS=build-tools_r19.0.1-linux.zip
  - ANDROID_SDK=android-sdk_r22.6.1-linux.tgz

matrix:
- ANDROID_SDKS=android-19,sysimg-19  ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

branches:
  only:
    - master

before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - wget http://dl.google.com/android/${ANDROID_SDK} -O android-sdk.tgz
  - tar xzf android-sdk.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  # install android build tools
  - wget https://dl-ssl.google.com/android/repository/${BUILD_TOOLS} -O build-tools-linux.zip
  - unzip build-tool-linux.zip -d $ANDROID_HOME

  # Install required components.
  # For a full list, run `android list sdk -a --extended`
  - echo y | android update sdk --filter 1,2                        --no-ui --force
  - echo y | android update sdk --filter ${ANDROID_SDKS}            --no-ui --force
  - echo y | android update sdk --filter extra-android-support      --no-ui --force
  - echo y | android update sdk --filter extra-android-m2repository --no-ui --force

  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - chmod +x ./wait_for_emulator.sh
  - ./wait_for_emulator.sh
  # Unlock screen
  - adb shell input keyevent 82 &

script:
  - ./gradlew androidTest
