language: java
jdk: oraclejdk7

env:
  global:
    - TERM=dumb
    - BUILD_TOOLS=build-tools-19.1.0
    - ANDROID_SDK_FILE=android-sdk_r22.6.2-linux.tgz
  matrix:
      - ANDROID_SDKS=android-19,sysimg-19  ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

branches:
  only:
    - master

before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - curl http://dl.google.com/android/${ANDROID_SDK_FILE} | tar xz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  # Install required components.
  # For a full list, run `android list sdk -a --extended`
  - echo y | android update sdk --filter tools,platform-tools       --no-ui --force
  - echo y | android update sdk --filter ${BUILD_TOOLS}             --no-ui --force
  - echo y | android update sdk --filter ${ANDROID_SDKS}            --no-ui --force
  - echo y | android update sdk --filter extra-android-support      --no-ui --force
  - echo y | android update sdk --filter extra-android-m2repository --no-ui --force

  # Create and start emulator
  - echo no | android create avd --force -n test -t ${ANDROID_TARGET} --abi ${ANDROID_ABI}
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - chmod +x ci/wait_for_emulator.sh
  - ci/wait_for_emulator.sh
  # Unlock screen
  - adb shell input keyevent 82 &

script:
  - ./gradlew connectedAndroidTest
